name: EditAss
ssl_verify: false
show_channel_urls: true
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/bioconda/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/menpo/
dependencies:
  - _libgcc_mutex=0.1=main
  - _pytorch_select=0.2=gpu_0
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1=py36_0
  - cffi=1.14.0
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.5=cuda10.0_0
  - intel-openmp=2020.0=166
  #- ld_impl_linux-64=2.33.1
  #- libedit=3.1.20181209
  - libffi=3.2.1
  #- libgcc-ng=9.1.0
  #- libgfortran-ng=7.3.0
  #- libstdcxx-ng=9.1.0
  - mkl=2020.0=166
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  #- ncurses=6.2
  - ninja=1.9.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openssl=1.1.1g
  - pip=20.0.2=py36_1
  - pycparser=2.20=py_0
  - python=3.6.10
  - pytorch=1.2.0
  #- readline=8.0
  - setuptools=46.1.3=py36_0
  - six=1.14.0=py36_0
  - sqlite=3.31.1
  - tk=8.6.8
  - wheel=0.34.2=py36_0
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - absl-py==0.9.0
    - astor==0.8.1
    - boto==2.49.0
    - boto3==1.13.3
    - botocore==1.16.3
    - cachetools==4.1.0
    - chardet==3.0.4
    - click==7.1.2
    - docopt==0.6.2
    - docutils==0.15.2
    - fasttext==0.9.2
    - fire==0.3.1
    - gast==0.2.2
    - gensim==3.8.3
    - google-auth==1.14.1
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - grpcio==1.28.1
    - h5py==2.10.0
    - idna==2.9
    - jmespath==0.9.5
    - joblib==0.14.1
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - markdown==3.2.1
    - nltk==3.5
    - oauthlib==3.1.0
    - opt-einsum==3.2.1
    - protobuf==3.11.3
    - psutil==5.7.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybind11==2.5.0
    - python-dateutil==2.8.1
    - regex==2020.4.4
    - requests==2.23.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - s3transfer==0.3.3
    - scikit-learn==0.22.2.post1
    - scipy==1.4.1
    - smart-open==2.0.0
    - stanfordnlp==0.2.0
    - tensorboard==2.1.1
    - tensorflow==2.1.0
    - tensorflow-estimator==2.1.0
    - termcolor==1.1.0
    - theano==1.0.4
    - tqdm==4.46.0
    - urllib3==1.25.9
    - werkzeug==1.0.1
    - wrapt==1.12.1
    - xdg==4.0.1

